services:
  - type: web
    name: pathikbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m bot.main
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        value: pathikbot
      - key: STORAGE_CHANNEL_ID
        sync: false
      - key: COMPANY_NAME
        sync: false
      - key: OFFICER_NAME
        sync: false
      - key: DESIGNATION
        sync: false
      - key: POSTING_AREA
        sync: false
      - key: MOTORCYCLE_BRAND
        sync: false
      - key: DEPO_NAME
        sync: false
